name: Build Curriculum Vitae

on:
  push:
    branches:
      - '**' # All branches
  workflow_dispatch: # Manual build

jobs:
  build-french-cv:
    runs-on: ubuntu-latest
    container:
      image: sauerburger/pdflatex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX curriculum vitae
        working-directory: ./src/fr/
        run: pdflatex ./curriculum-vitae.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: curriculum-vitae-fr
          path: ./src/fr/curriculum-vitae.pdf
          retention-days: 1

  build-nglish-cv:
    runs-on: ubuntu-latest
    container:
      image: sauerburger/pdflatex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX curriculum vitae
        working-directory: ./src/en/
        run: pdflatex ./curriculum-vitae.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: curriculum-vitae-en
          path: ./src/en/curriculum-vitae.pdf
          retention-days: 1
